## this is a YAML configuration file.  for more details see <>.  as in
## Python, # denotes the remainder of the line is a comment.

## some boilerplate GAE configuration
application: your-appname-here
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

## begin the list of URL handlers
handlers:

## a convenient place to put static elements: CSS, JS, images, etc.
- url: /static
  static_dir: static

## insert two commonly requested static elements.  creating these
## means that your logs don't fill up with spew from browsers and
## search engine crawlers.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
## EX. what is the trade-off between doing this and not bothering? 

- url: /.*
  script: app.py
